### ISSUE TITLE
[Persist emails before send]

### ISSUE THREAD

**Issue by calippo** [buildo/mailo#59]
## requirements

- The user should be allowed to choose between at-most-once and at-least-once semantics
- In at-least-once emails should be persisted in a queue before sending
- In at-least-once emails should be sent with semantic at-least-once

## specs

- Implemented with akka persistence
- Stored on leveldb
- Store offset in separate file

## misc
{optional: other useful info}

## sub-issues

- [x] dispatch on delivery type #61 **[calippo]**
- [x] persist messages before send #66 **[calippo]**
- [x] convert dryrun in integration test #69

**Comment by calippo** [comment]
closing macro issue, smaller related issue remain open
